---
- name: Add repo key
  apt_key:
    id: "0xd68fa50fea312927"
    keyserver: keyserver.ubuntu.com
    state: present
  tags: install

- name: add repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2
    update_cache: yes
  tags: install

- name: Install mongodb
  apt:
    name: mongodb-org
    state: latest
  tags: install

- name: Enable and start mongo
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install